#!/usr/bin/python

from langdetect import detect
from langdetect import detect_langs
import sys

try:
	text = sys.argv[1]
except IndexError:
	exit(0)

try:
	targ_lang = sys.argv[2]
except IndexError:
	targ_lang = "en"


if(text == "" ):
	exit(0)

lang = str(detect_langs(text))

if(lang.find(",") == -1 and lang[1:3] == targ_lang):
	exit(1)
else:
	exit(0)

